version: '3.8'
services:
  aquabrainapi:
    image: ghcr.io/jasperdemmers/aquabrainapi:main
    ports:
      - 8080:8080
    environment:
      - BASIC_AUTH_USERNAME=
      - BASIC_AUTH_PASSWORD=
      - MYSQL_HOST=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
